# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # common
  config.vm.box = "centos7"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box 
  end

  config.vm.provision :shell, :path => "./provisioning/common/init.sh"
  config.vm.provision :shell, :path => "./provisioning/common/add-hosts.sh"

  # master01
  config.vm.define :master01 do |master01|
    master01.vm.hostname = "master01"
    master01.vm.network :private_network, ip: "192.168.222.70"
    master01.vm.provision :shell, :path => "./provisioning/master01/install-packages.sh"
    master01.vm.provision :shell, :path => "./provisioning/master01/docker-registry.sh"
    master01.vm.provision :shell, :path => "./provisioning/master01/etcd.sh"
    master01.vm.provision :shell, :path => "./provisioning/master01/k8s-master.sh"
  end

  # node01
  config.vm.define :node01 do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network :private_network, ip: "192.168.222.71"
    node01.vm.provision :shell, :path => "./provisioning/node/docker.sh"
    node01.vm.provision :shell, :path => "./provisioning/node/k8s-node.sh"
    node01.vm.provision :shell, :path => "./provisioning/node/flannel.sh"
  end

  # node02
  config.vm.define :node02 do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network :private_network, ip: "192.168.222.72"
    node02.vm.provision :shell, :path => "./provisioning/node/docker.sh"
    node02.vm.provision :shell, :path => "./provisioning/node/k8s-node.sh"
    node02.vm.provision :shell, :path => "./provisioning/node/flannel.sh"
  end

end
